modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GENERAL PUBLIC LICENSE"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="epicfight" #mandatory
version="19.5.19" #mandatory
displayName="Epic Fight" #mandatory
#displayURL="https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod" #optional
#logoFile="epicfight.png" #optional
#credits="Gui Brabo(aka Metal), Nathan(aka Stel312)" #optional
#authors="Yesman" #optional
description='''Fight til u dead
'''

[[dependencies.epicfight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.3.5,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="BOTH"
