modLoader="javafml"
loaderVersion="[40,)"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId="epicdragonfight"
version="1.0.1"
displayName="EpicFight DragonEye Fix"
credits="..."
displayURL=""
authors="SuSen36"
description='''
   Let the enderdragon eye in the EpicFight shine!
'''

[[dependencies.epicdragonfight]]
   modId="forge"
   mandatory=true
   versionRange="[40.2.14,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.epicdragonfight]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"


[[dependencies.epicdragonfight]]
    modId="epicfight"
    mandatory=true
    versionRange="[18.5,)"
    ordering="AFTER"
    side="BOTH"